name: Python Lint (RationAI Standard)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  python-lint:
    uses: RationAI/.github/workflows/python-lint.yml@main
